### login as backoffice
POST localhost:8080/auth/login
Content-Type: application/json

{
  "userId": "a-6230265944",
  "password": "mohcine01"
}

### set password for agent
PUT localhost:8080/auth/password

### add an agent
POST localhost:8080/agent?bo=true
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "dounia aissi",
  "email": "dounia@aissi.ma",
  "phoneNumber": "212804261628",
  "balance": 1000000000,
  "threshold": 80000
}


### get the agent
GET localhost:8080/agent?user=a-7202159078

### debit from the account
PUT localhost:8080/agent/balance
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "agentId": "a-1576702643",
  "amount": 160000,
  "type": "DEBIT"
}

### update the threshold of an agent
PUT localhost:8080/agent/threshold
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "agentId": "a-7202159078",
  "newThreshold": 60000
}