spring:
    application:
        name: gateway

    cloud:
        gateway:

            discovery:
                locator:
                    enabled: true
                    lower-case-service-id: true
            routes:
                # auth route
                - id: auth
                  uri: lb://auth-service
                  predicates:
                    - Path=/auth/**

                # transfer route
                - id: transfer
                  uri: lb://transfer-service
                  predicates:
                    - Path=/transfer/**

                # wallet route
                - id: wallet
                  uri: lb://wallet-service
                  predicates:
                    - Path=/wallet/**

                # client route
                - id: client
                  uri: lb://client-service
                  predicates:
                    - Path=/client/**

                # recipient route
                -   id: recipient
                    uri: lb://client-service
                    predicates:
                        - Path=/recipient/**

                # discovery route
                - id: discovery
                  uri: http://localhost:8761
                  predicates:
                    - Path=/eureka/**

                # agent service
                - id: agent
                  uri: lb://agent-service
                  predicates:
                    - Path=/agent/**

                # notification service
                - id: pincode
                  uri: lb://pin-code-service
                  predicates:
                    - Path=/pincode/**

                # sms service
                - id: sms
                  uri: lb://sms-service
                  predicates:
                    - Path=/app-gw/**


server.port: 8080

eureka:
    client:
        serviceUrl:
            defaultZone: ${EUREKA_URI:http://localhost:8761}/eureka
    instance:
        prefer-ip-address: true
