spring:
    application:
        name: siron-service

    datasource:
        url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:tn}
        username: ${DB_USER:root}
        password: ${DB_PASS:12345678}
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        database-platform: org.hibernate.dialect.MySQLDialect
        open-in-view: false

    batch:
        job:
            enabled: false

eureka:
    client:
        service-url:
            defaultZone: ${EUREKA_URL:localhost:8761}/eureka/

server:
    port: 0