### test login through gateway
POST localhost:8080/auth/login
Content-Type: application/json

{
  "userId": "a-4572479942",
  "password": "mohcine01"
}

### access an endpoint in transfer
GET localhost:8080/transfer/test
Authorization: Bearer {{token}}