spring:

    main:
        allow-bean-definition-overriding: true
    application:
       name: email-service

    rabbitmq:
        host: ${RABBIT_HOST:localhost}
        port: ${RABBIT_PORT:5672}
        username: ${RABBIT_USER:guest}
        password: ${RABBIT_PASS:guest}
server:
    port: 0
